export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUSET";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCES";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGIST_REQUEST = "USER_REGIST_REQUEST";
export const USER_REGIST_SUCCESS = "USER_REGIST_SUCCES";
export const USER_REGIST_FAIL = "USER_REGIST_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
